// Code generated by protoc-gen-go.
// source: grpc
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc

It has these top-level messages:
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

var fileDescriptor0 = []byte{
	// 30 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x62, 0x49, 0x2f, 0x2a, 0x48,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x95, 0x1e, 0xd9, 0xef, 0x06, 0x00, 0x00, 0x00,
}
